version: '3.4'

services:

  customerdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  customer.api:
    image: customer.api
    build:
      context: .
      dockerfile: Api/Dockerfile


volumes:
  sql-volume: